name: Main org mode ast
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: run tests
        run: |
          bun run test:silent
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare files for lint
        uses: actions/checkout@master
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        if: steps.tschangeset.outputs.any_changed == 'true'
        run: bun run lint
