name: Publish Package to npmjs

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: run tests
        run: |
          bun run test:silent
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare files for lint
        uses: actions/checkout@master
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        if: steps.tschangeset.outputs.any_changed == 'true'
        run: bun run lint

  tagged-release:
    name: 'Tagged Release'
    runs-on: 'ubuntu-latest'
    needs: [tests, lint]
    steps:
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false

  # TODO: migrate to bun https://github.com/oven-sh/bun/issues/1976
  publish:
    needs: tagged-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: 'darkawower'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
